# Generated by Django 2.2.6 on 2020-02-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_manager', '0002_auto_20200208_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner_socios_protectores',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='slider',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
