# Generated by Django 2.2.6 on 2019-11-10 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('slug', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=200)),
                ('slug', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('email_2', models.CharField(blank=True, max_length=200, null=True)),
                ('tel_personal', models.IntegerField(blank=True, null=True)),
                ('tel_laboral', models.IntegerField(blank=True, null=True)),
                ('domicilio_fiscal', models.CharField(blank=True, max_length=200, null=True)),
                ('domicilio_postal', models.CharField(blank=True, max_length=200, null=True)),
                ('observacion', models.TextField(blank=True, max_length=300)),
                ('imagen', models.ImageField(blank=True, default='/media/perfil_socio/sin_imagen.jpg', null=True, upload_to='perfil_socio')),
                ('especialidad_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socio.Especialidad')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=200)),
                ('slug', models.CharField(blank=True, max_length=10, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socio.Categoria')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='CC_corriente',
            fields=[
                ('id_cc', models.AutoField(primary_key=True, serialize=False)),
                ('cuenta_numero', models.IntegerField(blank=True, null=True)),
                ('fecha_publicado', models.DateTimeField(auto_now_add=True)),
                ('cc_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socio.Estado')),
            ],
            options={
                'verbose_name': 'Cuenta Corriente',
                'verbose_name_plural': 'Cuenta Corriente',
            },
        ),
        migrations.CreateModel(
            name='CC_asiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.IntegerField(unique=True)),
                ('valor', models.FloatField(default='0.00')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socio.Concepto')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socio.CC_corriente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socio.Estado')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('cc_corriente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='socio.CC_corriente')),
                ('id_socio', models.AutoField(primary_key=True, serialize=False)),
                ('num_socio', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('dni', models.IntegerField(blank=True, null=True, unique=True)),
                ('cuit', models.IntegerField(blank=True, null=True, unique=True)),
                ('nombre_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Primer Nombre')),
                ('nombre_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Segundo Nombre')),
                ('apellido_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Primer Apellido')),
                ('apellido_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Segundo Apellido')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('borrado_logico', models.BooleanField(default=False, verbose_name='Borrado')),
                ('perfil', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socio.Perfil')),
                ('socio_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socio.Estado')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
            },
            bases=('socio.perfil', 'socio.cc_corriente'),
        ),
    ]
