# Generated by Django 2.2.6 on 2019-11-10 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('chair', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('init_year', models.CharField(blank=True, max_length=10, null=True)),
                ('end_year', models.CharField(blank=True, max_length=10, null=True)),
                ('about_description', tinymce.models.HTMLField()),
                ('about_honor_associates', models.CharField(max_length=500)),
                ('about_life_associates', models.CharField(max_length=500)),
                ('about_active_associates', models.CharField(max_length=500)),
                ('about_protector_associates', models.CharField(max_length=500)),
                ('about_follower_associates', models.CharField(max_length=500)),
                ('accounter_jr', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_member_acc_jr', to='about.BoardMember')),
                ('accounter_sr_1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_member_acc_sr_1', to='about.BoardMember')),
                ('accounter_sr_2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_member_acc_sr_2', to='about.BoardMember')),
                ('president', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_member_president', to='about.BoardMember')),
                ('secretary', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_member_secretary', to='about.BoardMember')),
                ('treasurer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_member_treasurer', to='about.BoardMember')),
                ('vicepresident', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_member_videpresident', to='about.BoardMember')),
                ('vocal_jr', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_member_jr', to='about.BoardMember')),
                ('vocal_sr', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_member_vocal_sr', to='about.BoardMember')),
            ],
        ),
    ]
